import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const sourcePath = path.join(__dirname, 'rhythms.source.json');
const dataTarget = path.join(projectRoot, 'src', 'data', 'strumRhythms.ts');

// Per-category fixed musical fields. Order also defines emit order.
const CATEGORY_FIXED = {
  'sixteen-beat-variation': { timeSignature: [4, 4], pulseNote: 'quarter', beatsPerBar: 4 },
  'three-four': { timeSignature: [3, 4], pulseNote: 'quarter', beatsPerBar: 3 },
  'twelve-eight': { timeSignature: [12, 8], pulseNote: 'dotted-quarter', beatsPerBar: 4 },
  'six-eight': { timeSignature: [6, 8], pulseNote: 'dotted-quarter', beatsPerBar: 2 },
  shuffle: { timeSignature: [4, 4], pulseNote: 'quarter', beatsPerBar: 4 },
  'slow-gogo': { timeSignature: [4, 4], pulseNote: 'quarter', beatsPerBar: 4 },
  'slow-rock': { timeSignature: [4, 4], pulseNote: 'quarter', beatsPerBar: 4 },
  calypso: { timeSignature: [4, 4], pulseNote: 'quarter', beatsPerBar: 4 },
  country: { timeSignature: [4, 4], pulseNote: 'quarter', beatsPerBar: 4 },
};
const CATEGORY_ORDER = Object.keys(CATEGORY_FIXED);

function categoryIdOf(id) {
  const m = /^(.*)_ex\d+$/.exec(id);
  if (!m) throw new Error(`Bad rhythm id "${id}" (expected "<category>_exNN")`);
  return m[1];
}

function exNoOf(id) {
  const m = /_ex(\d+)$/.exec(id);
  return m ? Number(m[1]) : 0;
}

async function main() {
  const raw = JSON.parse(await readFile(sourcePath, 'utf8'));
  const warnings = [];

  const entries = raw.map((src) => {
    const categoryId = categoryIdOf(src.id);
    const fixed = CATEGORY_FIXED[categoryId];
    if (!fixed) throw new Error(`Unknown category "${categoryId}" for ${src.id}`);

    const bars = Math.max(1, Math.round(src.bars ?? 1));
    const subdivision = src.subdivision;
    const cells = fixed.beatsPerBar * bars * subdivision; // valid steps: 0..cells-1

    const strokes = (src.strokes ?? [])
      .filter((stroke) => {
        if (stroke.step < 0 || stroke.step >= cells) {
          warnings.push(
            `${src.id}: dropped stroke step=${stroke.step} (out of range 0..${cells - 1}, subdiv=${subdivision}, bars=${bars})`,
          );
          return false;
        }
        return true;
      })
      .sort((a, b) => a.step - b.step);

    if (strokes.length === 0) warnings.push(`${src.id}: no valid strokes`);
    if ((src.confidence ?? '').includes('low')) warnings.push(`${src.id}: low-confidence draft`);

    const rhythm = {
      timeSignature: fixed.timeSignature,
      pulseNote: fixed.pulseNote,
      beatsPerBar: fixed.beatsPerBar,
      subdivision,
      bars,
      feelTiming: src.feelTiming,
      ...(src.swing != null ? { swing: src.swing } : {}),
      strokes,
      imageLeftPad: src.imageLeftPad,
      imageRightPad: src.imageRightPad,
    };

    return { id: src.id, categoryId, exNo: exNoOf(src.id), rhythm };
  });

  entries.sort(
    (a, b) =>
      CATEGORY_ORDER.indexOf(a.categoryId) - CATEGORY_ORDER.indexOf(b.categoryId) || a.exNo - b.exNo,
  );

  const stringifyStroke = (s) => {
    const parts = [`step: ${s.step}`, `dir: '${s.dir}'`];
    if (s.accent) parts.push('accent: true');
    if (s.tie) parts.push('tie: true');
    if (s.durationSteps != null) parts.push(`durationSteps: ${s.durationSteps}`);
    return `{ ${parts.join(', ')} }`;
  };

  const stringifyRhythm = (r) => {
    const lines = [];
    lines.push(`    timeSignature: [${r.timeSignature[0]}, ${r.timeSignature[1]}],`);
    lines.push(`    pulseNote: '${r.pulseNote}',`);
    lines.push(`    beatsPerBar: ${r.beatsPerBar},`);
    lines.push(`    subdivision: ${r.subdivision},`);
    lines.push(`    bars: ${r.bars},`);
    lines.push(`    feelTiming: '${r.feelTiming}',`);
    if (r.swing != null) lines.push(`    swing: ${r.swing},`);
    lines.push(`    imageLeftPad: ${r.imageLeftPad},`);
    lines.push(`    imageRightPad: ${r.imageRightPad},`);
    lines.push(`    strokes: [`);
    for (const s of r.strokes) lines.push(`      ${stringifyStroke(s)},`);
    lines.push(`    ],`);
    return lines.join('\n');
  };

  const body = entries
    .map((e) => `  '${e.id}': {\n${stringifyRhythm(e.rhythm)}\n  },`)
    .join('\n');

  const out = `import type { StrumRhythm } from './strumTypes';

// AUTO-GENERATED by scripts/buildRhythms.mjs from scripts/rhythms.source.json.
// Do not edit by hand; edit the JSON source and re-run \`node scripts/buildRhythms.mjs\`.
export const strumRhythms: Record<string, StrumRhythm> = {
${body}
};
`;

  await writeFile(dataTarget, out, 'utf8');

  const counts = {};
  for (const e of entries) counts[e.categoryId] = (counts[e.categoryId] ?? 0) + 1;
  console.log(`Generated ${entries.length} rhythms ->`, counts);
  if (warnings.length) {
    console.log(`\n${warnings.length} warning(s):`);
    for (const w of warnings) console.log(`  - ${w}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
